version: '2'
services:
  redis:
    image: redis
    ports:
      - 6399:6379

  proxy:
      build: .
      links:
        - redis
      command:
        python3 server/proxy.py

  proxy-http-server:
      build: .
      links:
        - redis
      ports:
        - 8080:80
      command:
        python3 server/proxy-server.py